spring:
  application:
    name: FileService
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      authentication-database: admin
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
